/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "outline": "#707974",
        "surface-dim": "#d3daef",
        "inverse-primary": "#95d3ba",
        "background": "#f9f9ff",
        "surface-container": "#e9edff",
        "on-background": "#141b2b",
        "surface": "#f9f9ff",
        "on-primary-container": "#80bea6",
        "secondary": "#5c5f60",
        "tertiary-fixed": "#ffdad5",
        "on-secondary-fixed": "#191c1d",
        "on-secondary-container": "#626566",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#0b513d",
        "on-primary": "#ffffff",
        "outline-variant": "#bfc9c3",
        "surface-variant": "#dce2f7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#b0f0d6",
        "primary-container": "#064e3b",
        "surface-container-high": "#e1e8fd",
        "surface-container-low": "#f1f3ff",
        "inverse-surface": "#293040",
        "secondary-fixed-dim": "#c5c7c8",
        "surface-tint": "#2b6954",
        "primary-fixed-dim": "#95d3ba",
        "tertiary-container": "#6b342d",
        "on-primary-fixed": "#002117",
        "on-tertiary-container": "#ea9e93",
        "error-container": "#ffdad6",
        "on-surface": "#141b2b",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dce2f7",
        "tertiary": "#4f1f19",
        "surface-bright": "#f9f9ff",
        "primary": "#003527",
        "on-tertiary-fixed": "#380d08",
        "on-surface-variant": "#404944",
        "secondary-fixed": "#e1e3e4",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-secondary-fixed-variant": "#454748",
        "secondary-container": "#e1e3e4",
        "inverse-on-surface": "#edf0ff",
        "on-tertiary-fixed-variant": "#6e372f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "120px",
        "base": "8px",
        "xs": "4px",
        "xl": "80px",
        "lg": "48px",
        "md": "24px",
        "sm": "12px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["30px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
